// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wZMuTUS-74Y_0IcYsXoMaDuVHnH5Avw',
    appId: '1:423605434651:web:82c99c2d376abd89553bbe',
    messagingSenderId: '423605434651',
    projectId: 'sokon-30008',
    authDomain: 'sokon-30008.firebaseapp.com',
    storageBucket: 'sokon-30008.firebasestorage.app',
    measurementId: 'G-328LGQMESY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATAdhpFUSC0qkMNXMa-0ewikLeimfBLFw',
    appId: '1:423605434651:android:8d5c80d7b9461f06553bbe',
    messagingSenderId: '423605434651',
    projectId: 'sokon-30008',
    storageBucket: 'sokon-30008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcu6zjoEPcTQfqECIgWksCAbBhTXTEfE',
    appId: '1:423605434651:ios:616ff19afd9251c7553bbe',
    messagingSenderId: '423605434651',
    projectId: 'sokon-30008',
    storageBucket: 'sokon-30008.firebasestorage.app',
    iosBundleId: 'com.example.sokon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpcu6zjoEPcTQfqECIgWksCAbBhTXTEfE',
    appId: '1:423605434651:ios:616ff19afd9251c7553bbe',
    messagingSenderId: '423605434651',
    projectId: 'sokon-30008',
    storageBucket: 'sokon-30008.firebasestorage.app',
    iosBundleId: 'com.example.sokon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_wZMuTUS-74Y_0IcYsXoMaDuVHnH5Avw',
    appId: '1:423605434651:web:0960bae89a1bc86a553bbe',
    messagingSenderId: '423605434651',
    projectId: 'sokon-30008',
    authDomain: 'sokon-30008.firebaseapp.com',
    storageBucket: 'sokon-30008.firebasestorage.app',
    measurementId: 'G-LJGB6HCLLF',
  );
}
